# Generated by Django 3.0.6 on 2020-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraBlogHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(max_length=50)),
                ('hashtags', models.CharField(blank=True, max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('comments', models.TextField()),
                ('post_old_or_new', models.BooleanField(default=False)),
            ],
        ),
    ]
