# Generated by Django 3.0.6 on 2020-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrabloghome',
            name='comments',
            field=models.IntegerField(),
        ),
    ]
