# Generated by Django 3.0.6 on 2020-09-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200923_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrabloghome',
            name='comments',
            field=models.TextField(),
        ),
    ]
