# Generated by Django 3.0.6 on 2020-09-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200923_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrabloghome',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
