# Generated by Django 3.0.6 on 2020-09-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200926_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userProfile',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
