# Generated by Django 3.0.6 on 2020-09-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('video_date', models.DateField(auto_now_add=True)),
                ('video_admin', models.CharField(max_length=50)),
                ('video_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='extrabloghome',
            name='comments_count',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
