# Generated by Django 3.0.6 on 2020-09-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200926_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories_filed',
            old_name='post_category',
            new_name='category',
        ),
    ]
