# Generated by Django 3.0.6 on 2020-09-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200926_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories_filed',
            new_name='CategoriesFiled',
        ),
    ]
