# Generated by Django 3.0.6 on 2020-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_singlepost_video_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='singlepost',
            name='video',
        ),
    ]
