# Generated by Django 3.0.6 on 2020-09-26 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200926_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlepost',
            old_name='video_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='singlepost',
            old_name='video_categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='singlepost',
            old_name='video_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='singlepost',
            old_name='video_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='singlepost',
            old_name='video_title',
            new_name='title',
        ),
    ]
